version: "3.8"
services:

  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
  mysql:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
    ports:
      - "3306:3306"
  activemq:
    image: symptoma/activemq:latest
    hostname: "0.0.0.0"
    ports:
      - "61616:61616"
      - "8161:8161"
    volumes:
      - ./jetty.xml:/opt/apache-activemq/conf/jetty.xml


